### ISSUE TITLE
obdm test takes a long time

### ISSUE THREAD

**Issue by lkwagner** [WagnerGroup/pyqmc#161]
In particular, test_pbc() is quite expensive, several factors more than the normal tests.

If it's not possible to speed it up, we could make an 'expensive' set of tests that are not run in the CI.

**Comment by willwheelera** [comment]
What things are important to test? Here are some possible things we could do to reduce time:

1. Right now it's calculating three obdms: all electrons, spin up and spin down. Could probably get rid of spin up without losing much. Could get rid of all electrons and just do spin down.
2. It's using a supercell of eight hydrogen atoms, to check supercell ability. Could change the supercell to four. Or not do a supercell, then we wouldn't check if kpoints work.
3. Could change primitive cell to H instead of H2
4. Does the Slater determinant obdm have higher variance without a cusp condition? If there are basis functions for H with a cusp condition maybe we can do a shorter vmc.

**Comment by lkwagner** [comment]
Definitely doing the test on a smaller system would go a long way. I think I would try that and see how the speed goes.

**Comment by lkwagner** [comment]
Closed by #168
